/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique;

import de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author anwer
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_connexion = new javax.swing.JButton();
        cb_liste = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTF_login = new javax.swing.JTextField();
        jLab_icon = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLab_login = new javax.swing.JLabel();
        jLab_mdp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 204));
        setMaximumSize(new java.awt.Dimension(554, 299));
        setMinimumSize(new java.awt.Dimension(554, 299));

        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 768));
        jPanel1.setLayout(null);

        bt_connexion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bt_connexion.setText("Connexion");
        bt_connexion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_connexionActionPerformed(evt);
            }
        });
        jPanel1.add(bt_connexion);
        bt_connexion.setBounds(340, 225, 110, 30);

        cb_liste.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cb_liste.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrateur", "Client", "Gérant" }));
        cb_liste.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cb_liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_listeActionPerformed(evt);
            }
        });
        jPanel1.add(cb_liste);
        cb_liste.setBounds(340, 83, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Type d'utilisateur");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 90, 140, 20);
        jPanel1.add(jTF_login);
        jTF_login.setBounds(340, 150, 140, 30);

        jLab_icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\anwer\\Desktop\\cryptographie-cles-cadenas-mot-passe-securite-icone-4965-96.png")); // NOI18N
        jPanel1.add(jLab_icon);
        jLab_icon.setBounds(30, 100, 130, 140);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(340, 190, 140, 30);

        jLab_login.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLab_login.setText("Login");
        jPanel1.add(jLab_login);
        jLab_login.setBounds(210, 160, 90, 20);

        jLab_mdp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLab_mdp.setText("Mot de passe");
        jPanel1.add(jLab_mdp);
        jLab_mdp.setBounds(210, 200, 90, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Si vous n'avez pas de compte, veuillez s'inscrire");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 270, 270, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("S'inscrire");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 260, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_listeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_listeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_listeActionPerformed

    private void bt_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_connexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_connexionActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    
        Insription ins = new Insription();
        ins.setVisible(true);
        this.setVisible(false);
        pack();
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new SyntheticaBlueLightLookAndFeel());

new Authentification().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_connexion;
    private javax.swing.JComboBox cb_liste;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLab_icon;
    private javax.swing.JLabel jLab_login;
    private javax.swing.JLabel jLab_mdp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTF_login;
    // End of variables declaration//GEN-END:variables
}
