/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique;
import de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;
import java.text.ParseException;
import  java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author anwer
 */
public class Chart extends javax.swing.JFrame {

    /**
     * Creates new form Chart
     */
 private void clock(){
 
 
Calendar cal=new GregorianCalendar();
int day=cal.get(Calendar.DAY_OF_MONTH);
 int mont=cal.get(Calendar.MONTH);
 int month=mont+1;
 int year =cal.get(Calendar.YEAR);
 int seconde=cal.get(Calendar.SECOND);
 int minute=cal.get(Calendar.MINUTE);
 int heure =cal.get(Calendar.HOUR);
 Lab_date.setText("Date :"+day+"/"+month+"/"+year);
 
 
 }
 
 
    public Chart() {
        initComponents();
        clock();
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt_backChart = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        Lab_date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("graph of the particular parameter");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 100, 180, 20);

        jPanel2.setLayout(null);

        bt_backChart.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bt_backChart.setForeground(new java.awt.Color(255, 255, 255));
        bt_backChart.setIcon(new javax.swing.ImageIcon("D:\\image pidf\\back-icone-5096-32.png")); // NOI18N
        bt_backChart.setText("Back");
        bt_backChart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_backChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_backChartMouseClicked(evt);
            }
        });
        bt_backChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backChartActionPerformed(evt);
            }
        });
        jPanel2.add(bt_backChart);
        bt_backChart.setBounds(0, 0, 100, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 110, 40);

        jPanel3.setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/statistical-power-icone-9129-32.png"))); // NOI18N
        jButton1.setText("Availability bar chart");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jButton1);
        jButton1.setBounds(10, 12, 220, 39);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/kpercentage-icone-6082-32.png"))); // NOI18N
        jButton2.setText("Availability percentage  bar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jButton2);
        jButton2.setBounds(10, 59, 220, 39);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("D:\\image pidf\\Score-icon.png")); // NOI18N
        jButton3.setText("Availability score  bar");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(10, 110, 220, 39);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 90, 240, 150);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Paramter", "User", "Offer", "Administrator", "" }));
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(30, 20, 130, 21);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\anwer\\Desktop\\valider 16X.png")); // NOI18N
        jButton4.setText("OK");
        jPanel4.add(jButton4);
        jButton4.setBounds(60, 60, 80, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(330, 120, 210, 120);

        Lab_date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Lab_date.setForeground(new java.awt.Color(0, 0, 102));
        Lab_date.setText("Date");
        jPanel1.add(Lab_date);
        Lab_date.setBounds(460, 10, 110, 14);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 20, 10, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_backChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backChartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_backChartActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bt_backChartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_backChartMouseClicked
        // TODO add your handling code here:
         SuperAdmin ins = new SuperAdmin();
        ins.setVisible(true);
        this.setVisible(false);
        pack();
    }//GEN-LAST:event_bt_backChartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    try {
                        UIManager.setLookAndFeel(new SyntheticaBlueLightLookAndFeel());
                    } catch (ParseException ex) {
                        Logger.getLogger(Chart.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Chart.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Chart().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lab_date;
    private javax.swing.JButton bt_backChart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
